version: "3.9"

services:
  db-init:
    build:
      context: ./data
    container_name: mangahub-db-init
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=${DB_PATH}
      - SQL_FILE=${SQL_FILE}
    restart: "no"
  api-server:
    build:
      context: .
      dockerfile: cmd/api-server/Dockerfile
    container_name: mangahub-api
    depends_on:
      - db-init
    volumes:
      - ./data:/data
    environment:
      - API_PORT=${API_PORT}
      - DB_PATH=${DB_PATH}
    ports:
      - "${API_PORT}:${API_PORT}"

  tcp-server:
    build:
      context: .
      dockerfile: cmd/tcp-server/Dockerfile
    container_name: mangahub-tcp
    depends_on:
      - db-init
    volumes:
      - ./data:/data
    environment:
      - PORT=${TCP_PORT}
      - DB_PATH=${DB_PATH}
    ports:
      - "${TCP_PORT}:${TCP_PORT}"

  udp-server:
    build:
      context: .
      dockerfile: cmd/udp-server/Dockerfile
    container_name: mangahub-udp
    depends_on:
      - db-init
    volumes:
      - ./data:/data
    environment:
      - PORT=${UDP_PORT}
      - DB_PATH=${DB_PATH}
    ports:
      - "${UDP_PORT}:${UDP_PORT}"

  grpc-server:
    build:
      context: .
      dockerfile: cmd/grpc-server/Dockerfile
    container_name: mangahub-grpc
    depends_on:
      - db-init
      - tcp-server
    volumes:
      - ./data:/data
    environment:
      - PORT=${GRPC_PORT}
      - DB_PATH=${DB_PATH}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"

volumes:
  data:
