syntax = "proto3";
package manga;
option go_package = "mangahub/proto/manga;mangapb";

service MangaService {
    rpc GetManga(GetMangaRequest) returns (MangaResponse);
    rpc SearchManga(SearchRequest) returns (SearchResponse);
    rpc UpdateProgress(ProgressRequest) returns (ProgressResponse);
}

message GetMangaRequest {
    string id = 1;
}

message MangaResponse {
    string id = 1;
    string title = 2;
    string author = 3;
}

message SearchRequest {
    string keyword = 1;
}

message SearchResponse {
    repeated MangaResponse results = 1;
}

message ProgressRequest {
    string manga_id = 1;
    string user_id = 2;
    int32 chapter = 3;
}

message ProgressResponse {
    bool ok = 1;
}
